### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by jtopjian**
This PR contains a handful of updates. Changes are succinctly described in the commit messages. 

@crayfishx I noticed a 3.0 release was made, so I figured I would modify the acceptance tests to work off of that. I copied the test fixtures from the main repo since I needed to change the paths to work with the Docker image. I also disabled the encryption plugin. This should all be fine, but just a heads up.

I also had to make a small change to the actual HTTP client to set the `Content-Type` header to `application/json`.

Please let me know if you have any questions.

If this all looks good, I would like to get Travis integrated into this repo. Since tests can now be run entirely with the Docker container, Travis can manage testing and releases. Usual Travis bootstrapping will need to be done, though.

_edit_: Oh, if 3.0 shouldn't be used (yet), let me know and I'll reconfigure things so tests are run against both 2.5 and 3.0.

### CODE REVIEW

**Comment by beddari** [comment]
I think we suddenly have msgpack as default, which is why you needed to set content type. Awesome, this looks good to me.

Also, are you going to Gent this year https://twitter.com/safespring/status/1067756181156970498

**Comment by beddari** [comment]
Travis is already enabled for the org so I think Craig could just add that to this repo

**Comment by jtopjian** [comment]
> Also, are you going to Gent this year

Cool!

I might. I'll be in Rome the week prior so I need to see if I can extend the trip abroad.

**Comment by jtopjian** [comment]
> Awesome, this looks good to me.

I'm going to go ahead and merge this. It'll bring this library up to date and let me publish the Terraform Provider.

Thanks, Jan!

**Pull request merged**
